In [ ]:
# Experimet 10 - Study of pandas library
# Naman Bothra
# PRN - 25070123078

In [ ]:
# Introduction to pandas library
# Pandas - Panel Data
# Used for : Structure data
# EDA
# Data cleaning

In [1]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [2]:
# Create DataFrame
data = {
    "Name":["a","b","c"],
    "Marks":[85,90,70]
}
df = pd.DataFrame(data)
print(df)

  Name  Marks
0    a     85
1    b     90
2    c     70

In [6]:
# structure of data frame i.e. (column name,shape,size,dimension)
print(df.shape)
print(df.ndim)
print(df.size)
print(df.columns)

(3, 2)
2
6
Index(['Name', 'Marks'], dtype='object')

In [9]:
# check data type of each column
print(df.dtypes)

Name     object
Marks     int64
dtype: object

In [10]:
# access individual columns
df["Name"]

0    a
1    b
2    c
Name: Name, dtype: object

In [15]:
# Access name of first row
print(df.loc[0,"Name"])
print(df.loc[0,"Marks"])
print(df.iloc[2,1])

a
85
70

In [25]:
# add a new column
df["Grade"] = ["First Class","Distinction","Second class"]
print(df)

  Name  Marks         Grade
0    a     88   First Class
1    b     90   Distinction
2    c     70  Second class

In [17]:
# Update data in datarame
# change marks of student to 88
df.iloc[0,1]=88
print(df)

  Name  Marks         Grade
0    a     88   First Class
1    b     90   Distinction
2    c     70  Second class

In [26]:
# delete a column
df.drop("Grade",axis=1,inplace=True)
print(df)

  Name  Marks
0    a     88
1    b     90
2    c     70

In [27]:
# perform basic statistical analysis
mean1 = df["Marks"].mean()
print(mean1)

82.66666666666667

In [28]:
min1 = df["Marks"].min()
print(min1)

70

In [29]:
max1 = df["Marks"].max()
print(max1)

90

In [31]:
# apply condition to print values from dataframe

df[df["Marks"]>80]

  Name  Marks
0    a     88
1    b     90